version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - pgadmin-data:/var/lib/postgresql/data
    restart: always
    env_file:
      ./.env
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      ./.env
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/.pgadmin
    depends_on:
      - postgres

volumes:
  pgadmin-data:
